# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20171128_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=10, unique=True)),
                ('HostName', models.CharField(max_length=50)),
                ('Info', models.CharField(max_length=1024)),
                ('AddTime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectID', models.CharField(max_length=10, unique=True)),
                ('ProjectName', models.CharField(max_length=50, unique=True)),
                ('ProjectFrom', models.CharField(max_length=50)),
                ('ProjectUser', models.CharField(max_length=50, unique=True)),
                ('ProjectMsg', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
