# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_auto_20180716_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectall',
            name='ProjectUser',
            field=models.CharField(max_length=50),
        ),
    ]
