# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_auto_20180718_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectall',
            name='ProjectID',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
